config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  #root "articles#index"
  root "pawmigo#index"
  resources :user, only: [:index, :edit,]
  resources :pets 
  resources :schedules
  resources :notes
  resources :photos, only: [:edit, :update]
  resources :pawmigo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  pet_id     :integer          not null
#
# Indexes
#
#  index_notes_on_pet_id  (pet_id)
#
# Foreign Keys
#
#  pet_id  (pet_id => pets.id)
#
class Note < ApplicationRecord
  belongs_to :pet
end

app/models/pet.rb
# == Schema Information
#
# Table name: pets
#
#  id         :integer          not null, primary key
#  breed      :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_pets_on_user_id  (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Pet < ApplicationRecord
  belongs_to :user
  belongs_to :schedule
  has_many :schedules
  has_many :notes
  has_many :photos
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  owner_id   :integer          not null
#  pet_id     :integer          not null
#
# Indexes
#
#  index_photos_on_owner_id  (owner_id)
#  index_photos_on_pet_id    (pet_id)
#
# Foreign Keys
#
#  owner_id  (owner_id => owners.id)
#  pet_id    (pet_id => pets.id)
#
class Photo < ApplicationRecord
  belongs_to :pet
  belongs_to :user
  #belongs_to :owner, class_name: "User"
end

app/models/schedule.rb
# == Schema Information
#
# Table name: schedules
#
#  id         :integer          not null, primary key
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  pet_id     :integer          not null
#
# Indexes
#
#  index_schedules_on_pet_id  (pet_id)
#
# Foreign Keys
#
#  pet_id  (pet_id => pets.id)
#
class Schedule < ApplicationRecord
  belongs_to :pet
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  private                :boolean
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  username               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_username              (username) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 validates :username, presence: true, uniqueness: { case_sensitive: false }
 has_many :pets
 #has_many :photos
 has_many :own_photos, class_name: "Photo", foreign_key: "owner_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_forgery_protection
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end
end

app/controllers/pawmigo_controller.rb
class PawmigoController < ApplicationController
  def index
    
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    #@pet = Pet.find(params[:id])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  private

  def photo_params
    params.require(:photo).permit(:content, :image)
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photo_params)
      # Handle successful update, e.g., redirect to another page
    else
      render 'edit'
    end
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🐾 Pawmigo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://kit.fontawesome.com/4fb3303ae7.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <%= link_to root_path, class: "nav-link" do %>
            <i class="fa-solid fa-paw"></i>
          <% end %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "Home", root_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Pets", pets_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Notes", notes_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Schedules", schedules_path, class: "nav-link" %>
              </li>

              <li class="nav-item">
                <%= link_to "Edit profile", edit_user_registration_path, class: "nav-link" %>
              </li>

              <li class="nav-item">
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>

            </ul>
          </div>
        </div>
      </nav>
   <% end %>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  
  </body>
</html>

app/views/notes/_simple-note.html.erb
<!-- app/views/notes/_simple-note.html.erb -->
<p>
 note
</p>

app/views/notes/index.html.erb
<!-- app/views/notes/index.html.erb -->
<h1>All Notes</h1>
<ul>
  <% @notes.each do |note| %>
    <li><%= note.content %></li>
  <% end %>
</ul>

<div class="card bg-dark text-white" style="width: 20rem;">
  <img src="https://lh3.googleusercontent.com/p/AF1QipNcvxXF0_ovUidm0nXfqWP83k2PNYUP7zgIViZU=s1360-w1360-h1020" class="card-img opacity-50"  alt="...">
  <div class="card-img-overlay">
    <h5 class="card-title">Pet Name</h5>
    <h6>Note Name</h6>
    <h6>Note Date</h6>
    <button type="button" class="btn btn-dark">View this Note</button>
  </div>
</div>

app/views/notes/show.html.erb
hello notes

app/views/pawmigo/index.html.erb
<div class="hero">
  <img  src="https://lh3.googleusercontent.com/p/AF1QipPnNHCXOb17HbqdCzl_S9vw-CXN5sQcOUUGlRPZ=s1360-w1360-h1020" alt="Hero Image" class="hero-image">
  <div class="hero-content">
    <h1>PAWMIGO</h1>
    <p>Something inspirational about pets</p>
      <div class="d-grid gap-2 d-md-block">
        <button class="btn btn-info" type="button"><%= link_to "Sign in", new_user_session_path, class: "nav-link" %></button>
        <button class="btn btn-info" type="button"><%= link_to "Sign up", new_user_registration_path, class: "nav-link" %></button>
      </div>
  </div>
</div>

app/views/pets/index.html.erb
<!-- app/views/pets/index.html.erb -->
<h1>Pet Name</h1>
<ul>
  <% @pets.each do |pet| %>
    <li><%= pet.name %></li>
  <% end %>
</ul>

<%= link_to "View Schedules", schedules_path %>

<%= link_to "View Notes", notes_path %>
<div class="card" style="width: 18rem;">
  <img src="https://lh3.googleusercontent.com/p/AF1QipNcvxXF0_ovUidm0nXfqWP83k2PNYUP7zgIViZU=s1360-w1360-h1020" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Pets Name</h5>
    <a href="<%= pets_path %>" class="btn btn-primary">More Details</a>
  </div>
</div>

app/views/pets/show.html.erb
<!-- app/views/pets/index.html.erb -->
<h1>Pet Name: <%= @pet.name %></h1>

<%= link_to "View Schedules", schedules_path %>

<%= link_to "View Notes", notes_path %>

<div class="card mb-3" style="max-width: 1140px;">
  <div class="row g-0">
    <div class="col-md-4">
      <div class="card-body">
        <!-- START OF ACCORDION -->
        <div class="accordion accordion-flush" id="accordionFlushExample">
          <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingOne">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                NOTES
              </button>
            </h2>
            <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
              <div class="accordion-body"><%= render 'notes/simple-note' %></div>
              <button type="button" class="btn btn-primary">Edit Note</button>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingTwo">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                SHEDULE
              </button>
            </h2>
            <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
              <div class="accordion-body"><%= render 'schedules/simple-schedule' %></div>
              <button type="button" class="btn btn-primary">Edit Schedule</button>
            </div>
          </div>
        </div>
        <!-- END OF ACCORDION -->
      </div>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <img src="https://lh3.googleusercontent.com/p/AF1QipNcvxXF0_ovUidm0nXfqWP83k2PNYUP7zgIViZU=s1360-w1360-h1020" class="img-fluid rounded-start" alt="...">
      </div>
    </div>
  </div>
</div>

app/views/photos/edit.html.erb
<!-- app/views/photos/edit.html.erb -->
<h1>Edit Photo</h1>
<%= form_for @photo, url: photo_path(@photo), method: :patch, html: { multipart: true } do |f| %>
  <!-- Photo fields and file input here -->
  <%= f.label :content %>
  <%= f.text_area :content %>

  <!-- File upload field -->
  <%= f.label :image %>
  <%= f.file_field :image %>

  <%= f.submit "Update Photo" %>
<% end %>

=begin code for linking this page to the PETS page
 <%= link_to "Edit Photo", edit_photo_path(@photo) %> 
=end

app/views/schedules/_simple-schedule.html.erb
<!-- app/views/schedule/_simple-schedule.html.erb -->
<p>Schedule</p>

app/views/schedules/index.html.erb
<!-- app/views/schedules/index.html.erb -->
<h1>All Schedules</h1>
<ul>
  <% @schedules.each do |schedule| %>
    <li><%= schedule.content %></li>
  <% end %>
</ul>

<div class="card bg-dark text-white" style="width: 20rem;">
  <img src="https://lh3.googleusercontent.com/p/AF1QipNcvxXF0_ovUidm0nXfqWP83k2PNYUP7zgIViZU=s1360-w1360-h1020" class="card-img opacity-50"  alt="...">
  <div class="card-img-overlay">
    <h5 class="card-title">Pet Name</h5>
    <h6>Schedule Name</h6>
    <h6>Schedule Date</h6>
    <button type="button" class="btn btn-dark">View this Schedule</button>
  </div>
</div>

app/views/user/index.html.erb
<div class="wrap">
<div>
 <h1>Hello!</h1>
</div>

<ul class="list-group col-4">
  <li class="list-group-item d-flex align-items-center"> 🦖 Pets
  <div class="justify-content-end">
  <button type="button" class="btn btn-primary">View all</button>
  <button type="button" class="btn btn-primary">+</button>
  </div>
  </li>

  <li class="list-group-item"> ✍️ Notes
   <button type="button" class="btn btn-primary">View all</button>
  <button type="button" class="btn btn-primary">+</button>
  </li>

  <li class="list-group-item"> 📅 Schedules
   <button type="button" class="btn btn-primary">View all</button>
  <button type="button" class="btn btn-primary">+</button>
  </li>
</ul>

<%= link_to "Edit profile", edit_user_registration_path, class: "nav-link" %>
</div>